### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by szybkijanek** [s0danissa/3_phase_full_wave_rectifier#2]
Hi, i can't open Simulink model, can You reupload file again?

**Comment by s0danissa** [comment]
> Hi, i can't open Simulink model, can You reupload file again?

Hi! What exactly prevents you from opening it? It opens well on my machine (I have MATLAB R2020a)

**Comment by szybkijanek** [comment]
So, i have this message on console:
>> simulink
'three-phase-full-wave-rectifier.slx' is not a valid Simulink model file name.  For more information see the save_system documentation.
'1.slx' is not a valid Simulink model file name.  For more information see the save_system documentation.
1.slx is same file after change name to "1". My version of Matlab is 2020b. Screen error in attachment
![error](https://user-images.githubusercontent.com/51792174/147920195-0aeb354f-c323-4917-955f-843212464309.jpg)

**Comment by s0danissa** [comment]
This problem has been discussed in a previous issue, try changing dashes to underscores in the filename. It seems that some version of Simulink do not understand dashes.
